# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
     graphiql:
        patterns:
          - "graphiql"
          - "@graphiql/*"
     yoga:
        patterns:
          - "envelop"
          - "graphql-yoga"
          - "@envelop/*"
          - "@graphql-yoga/*"
      graphql-armor:
        patterns:
          - "@escape.tech/graphql-armor-*"
      radix:
        patterns:
          - "@radix-ui/*"
          - "@radix/*"
      stripe:
        patterns:
          - "@stripe/"
          - "stripe"
      urql:
        patterns:
          - "@urql/"
          - "urql"
      sentry:
        patterns:
          - "@sentry/"
          - "sentry"
      trpc:
        patterns:
          - "@trpc/"
          - "trpc"
      supertokens:
        patterns:
          - "supertokens"
          - "@supertokens/*"
          - "supertokens-*"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "daily"
