dist:
  version: 0.140.0
  name: otelcol-custom
  description: Custom OTel Collector distribution
  output_path: ./otelcol-custom

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.140.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.140.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.140.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor
      v0.140.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.140.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.140.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhouseexporter v0.140.0

extensions:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension
      v0.140.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.140.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.140.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage
      v0.140.0
  - gomod: github.com/graphql-hive/console/docker/configs/otel-collector/extension-hiveauth v0.0.0
    path: ./extension-hiveauth
    name: hiveauthextension # when using local extensions, package name is required, otherwise you get "missing import path"
  - gomod: github.com/graphql-hive/console/docker/configs/otel-collector/extension-statsviz v0.0.0
    path: ./extension-statsviz
    name: statsvizextension
