extensions:
  health_check:
    endpoint: '0.0.0.0:13133'
receivers:
  kafka:
    brokers:
      - ${KAFKA_BROKER}
    topic: otel-traces
    encoding: otlp_proto
    group_id: otel-collector-egress
    session_timeout: 30s
processors:
  batch:
    timeout: 5s
    send_batch_size: 8000
exporters:
  debug:
    verbosity: basic
  clickhouse:
    endpoint: ${CLICKHOUSE_PROTOCOL}://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}?dial_timeout=10s&compress=lz4&async_insert=1&wait_for_async_insert=0
    database: default
    async_insert: true
    username: ${CLICKHOUSE_USERNAME}
    password: ${CLICKHOUSE_PASSWORD}
    create_schema: false
    ttl: 720h
    compress: lz4
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
service:
  extensions:
    - health_check
  telemetry:
    logs:
      level: INFO
      encoding: json
      output_paths: ['stdout']
      error_output_paths: ['stderr']
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 10254
  pipelines:
    traces:
      receivers: [kafka]
      processors:
        - batch
      exporters:
        - clickhouse
        # - debug
