on:
  workflow_call:

jobs:
  validate-changesets:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          actor: changeset-validation

      - name: validate changeset packages
        run: pnpm tsx scripts/validate-changesets.ts
