name: docs-e2e

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: packages/web/docs

    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          codegen: false
          actor: docs-e2e

      - name: build docs
        run: pnpm build

      - name: install playwright browsers
        run: pnpm exec playwright install chromium

      - name: run playwright tests
        run: pnpm exec playwright test --config=e2e/playwright.config.ts --project=chromium
        env:
          CI: true
          BASE_URL: http://localhost:3000

      - name: upload playwright report
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        if: ${{ failure() }}
        with:
          name: docs-playwright-report
          path: packages/web/docs/.playwright/
          retention-days: 7
